services:
  swarmui:
    image: swarmui
    user: ${HOST_UID:-1000}:${HOST_GID:-1000}
    cap_drop:
      - ALL
    build:
      context: .
      args:
        UID: ${HOST_UID:-1000}
      dockerfile: launchtools/StandardDockerfile.docker
    container_name: swarmui
    # uncomment `network_mode: host` if you want to access other services on the host network (eg a separated comfy instance)
    # network_mode: host
    volumes:
      - swarmdata:/SwarmUI/Data
      - swarmbackend:/SwarmUI/dlbackend
      - swarmdlnodes:/SwarmUI/src/BuiltinExtensions/ComfyUIBackend/DLNodes
      - swarmextensions:/SwarmUI/src/Extensions
      - ./Models:/SwarmUI/Models
      - ./Output:/SwarmUI/Output
      - ./src/BuiltinExtensions/ComfyUIBackend/CustomWorkflows:/SwarmUI/src/BuiltinExtensions/ComfyUIBackend/CustomWorkflows
    ports:
      - "7801:7801"
    depends_on:
      - mongo
    environment:
      SWARM_DB: mongodb
      SWARM_MONGO_CONNECTION: mongodb://mongo:27017
      SWARM_MONGO_DB: swarmui
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # change the count to the number of GPUs you want to use.
              count: 1
              capabilities: [gpu]
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
volumes:
  swarmdata:
    name: swarmdata
  swarmbackend:
    name: swarmbackend
  swarmdlnodes:
    name: swarmdlnodes
  swarmextensions:
    name: swarmextensions
  mongodata:
    name: mongodata
